AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Universal Auth Module Backend

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    Environment:
      Variables:
        USER_POOL_ID: !Ref UserPool
        USER_POOL_CLIENT_ID: !Ref UserPoolClient

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: UniversalAuthUserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: UniversalAuthClient
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH

  AuthApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  CognitoAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CognitoAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:AdminGetUser
                  - cognito-idp:InitiateAuth
                  - cognito-idp:SignUp
                  - cognito-idp:ConfirmSignUp
                  - cognito-idp:ResendConfirmationCode
                  - cognito-idp:ConfirmForgotPassword
                  - cognito-idp:ForgotPassword
                  - cognito-idp:AdminUpdateUserAttributes
                Resource: !GetAtt UserPool.Arn

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: auth.login_handler
      Role: !GetAtt CognitoAccessRole.Arn
      Events:
        LoginApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/login
            Method: post

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: auth.register_handler
      Role: !GetAtt CognitoAccessRole.Arn
      Events:
        RegisterApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/register
            Method: post

  ResetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: auth.reset_password_handler
      Role: !GetAtt CognitoAccessRole.Arn
      Events:
        ResetPasswordApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/reset-password
            Method: post

  VerifyEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: auth.verify_email_handler
      Role: !GetAtt CognitoAccessRole.Arn
      Events:
        VerifyEmailApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/verify-email
            Method: post

  ResendVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: auth.resend_verification_handler
      Role: !GetAtt CognitoAccessRole.Arn
      Events:
        ResendVerificationApi:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/resend-verification
            Method: post

Outputs:
  AuthApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref UserPool
  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref UserPoolClient